### ISSUE TITLE
Duplicate Link for YouTube

### ISSUE THREAD

**Issue by djm1176** [msu-csc232-fa19/hw00#1]
It appears the link for 'Pull Requests' under '**Prerequisites**' links to the 'Merge' video, and should instead link to this video: https://www.youtube.com/watch?v=d5wpJ5VimSU

**Comment by sethmabry8888** [comment]
Same for link to Rebase video, instead it opens Ignore. Here is Rebase: https://www.youtube.com/watch?v=SxzjZtJwOgo&frags=pl%2Cwn

Thanks for sharing the videos. Super helpful.

**Comment by professordaehn** [comment]
Thanks! The links have been updated (in the template repository). I'm not sure if that means future accepts of this assignment will be correct. However, the next time I create an assignment from this template, it'll be correct.
